version: 2 

sources:
  - name: raw
    schema: gz_raw_data
    description: the raw dataset of greenweez
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez
        freshness:
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
        columns:
          - name: orders_id || '-' || pdt_id
            tests:
              - unique
              - not_null
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: l'id de la commande
          - name: pdt_id
            description: l'id du produit
          - name: revenue
            description: le CA des produits
          - name: quantity
            description: la quantité de produits dans la commande
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: l'id des produits
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: le prix d'achat
      - name: ship
        identifier: raw_gz_ship
        description: ship of greenweez
        columns:
          - name: orders_id
            description: l'id de la livraison
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: les frais de livraison
          - name: shipping_fee_1
            description: les frais de livraison 1
          - name: logCost
            description: coûts logistiques
          - name: ship_cost
            description: frais de port
      - name: adwords
        identifier: raw_gz_adwords
        description: coûts et résultats campagne pub sur adwords
        columns:
          - name: date_date
            description: la date de la campagne
          - name: paid_source
            description: la source de la campagne
          - name: campaign_key
            description: l'id de la campagne
          - name: camPGN_name
            description: le nom de la campagne
          - name: ads_cost
            description: le coût de la campagne
          - name: impression
            description: nbre d'impressions
          - name: click
            description: nbre de clicks
      - name: bing
        identifier: raw_gz_bing
        description: coûts et résultats campagne pub sur bing
        columns:
          - name: date_date
            description: la date de la campagne
          - name: paid_source
            description: la source de la campagne
          - name: campaign_key
            description: l'id de la campagne
          - name: camPGN_name
            description: le nom de la campagne
          - name: ads_cost
            description: le coût de la campagne
          - name: impression
            description: nbre d'impressions
          - name: click
            description: nbre de clicks
      - name: criteo
        identifier: raw_gz_criteo
        description: coûts et résultats campagne pub sur criteo
        columns:
          - name: date_date
            description: la date de la campagne
          - name: paid_source
            description: la source de la campagne
          - name: campaign_key
            description: l'id de la campagne
          - name: camPGN_name
            description: le nom de la campagne
          - name: ads_cost
            description: le coût de la campagne
          - name: impression
            description: nbre d'impressions
          - name: click
            description: nbre de clicks
      - name: facebook
        identifier: raw_gz_facebook
        description: coûts et résultats campagne pub sur facebook
        columns:
          - name: date_date
            description: la date de la campagne
          - name: paid_source
            description: la source de la campagne
          - name: campaign_key
            description: l'id de la campagne
          - name: camPGN_name
            description: le nom de la campagne
          - name: ads_cost
            description: le coût de la campagne
          - name: impression
            description: nbre d'impressions
          - name: click
            description: nbre de clicks
models:
  - name: int_sales_margin
    description: suite à la jointure sales et product
    columns:
          - name: primary_key_sales
            description: la clé primaire
            tests:
              - unique
              - not_null
  - name: int_orders_operational2
    description: operational margin calcultation per order 
    columns:
      - name: operational_margin 
        description: Operational margin = margin + shipping fee - log_cost - ship_cost
  - name: finance_days2
    description: finance calculation per days
  - name: int_campaigns
    description: suite à la jointure de toutes les tables adwords, bing, criteo et facebook
    columns:
          - name: primary_key_campaign
            description: la clé primaire
            tests:
              - unique
              - not_null
          - name: paid_source
            tests:
              - not_null
          - name: campaign_name
            tests:
              - not_null
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null
          - name: click
            tests:
              - not_null
              