version: 2 

sources:
  - name: raw
    schema: gz_raw_data
    description: the raw dataset of greenweez
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez
        freshness:
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
        columns:
          - name: orders_id || '-' || pdt_id
            tests:
              - unique
              - not_null
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: l'id de la commande
          - name: pdt_id
            description: l'id du produit
          - name: revenue
            description: le CA des produits
          - name: quantity
            description: la quantité de produits dans la commande
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: l'id des produits
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: le prix d'achat
      - name: ship
        identifier: raw_gz_ship
        description: ship of greenweez
        columns:
          - name: orders_id
            description: l'id de la livraison
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: les frais de livraison
          - name: shipping_fee_1
            description: les frais de livraison 1
          - name: logCost
            description: coûts logistiques
          - name: ship_cost
            description: frais de port